import type { Metadata } from 'next';
import { Montserrat, Dela_Gothic_One } from 'next/font/google';
import Navbar from '@/components/layoutComponents/Navbar';
import Footer from '@/components/layoutComponents/Footer';
import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const montserrat = Montserrat({
	variable: "--font-montserrat",
	subsets: ["latin"],
});

const delaGothicOne = Dela_Gothic_One({
	variable: "--font-dela-gothic-one",
	subsets: ["latin"],
	weight: "400",
});

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`flex flex-col min-h-svh overflow-x-hidden overflow-y-scroll
                ${montserrat.variable} ${delaGothicOne.variable} antialiased`}
            >
                    <Navbar />
                <main className='flex-1'>
                    {children}
                </main>
                    <Footer />
            </body>
        </html>
    );
}
